name = "dad-ai-worker"
main = "worker.mjs"
compatibility_date = "2025-08-23"

[[d1_databases]]
binding = "DB"
database_name = "dad_ai_db"
database_id = "8cfebded-2834-4a5e-a4cc-31190c4f1bca"

[vars]
MAIL_FROM_DOMAIN = "dad-ai.online"
